name: Mirror to another repo

on:
  push:
    branches:
      - '**'     # any branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1. Pull down your source (full history)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Add the target repository
      - name: Add target remote
        run: |
          git remote add target \
            https://x-access-token:${{ secrets.GITLAB_ACCESS_TOKEN }}@git@gitlab.com:editheman/de_test.git

      # 3. Push everything (branches & tags) unmodified
      - name: Mirror push
        run: |
          git push target --mirror
