name: Mirror to another repo

on:
  push:
    branches:
      - '**'     # any branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1. Pull down your source (full history)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Add the target repository
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          # Create GitLab URL with token
          GITLAB_URL="https://oauth2:${GITLAB_TOKEN}@gitlab.com/editheman/de_test.git"
          
          # Add target and push
          git remote add target "${GITLAB_URL}"
          git push target --mirror
